name: flutter_ebook_app
version: 1.0.4+8
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"
description: A Flutter app for eBooks
dependencies:
  auto_route: ^10.0.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons.git
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.0.0
  google_fonts: ^6.2.1
  iridium_reader_widget:
    path: ./packages/iridium/reader_widget
  logman: ^0.0.21
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0
  pubspec_dependency_sorter: ^1.0.5
  riverpod_annotation: ^2.6.1
  sembast: ^3.8.5
  sembast_web: ^2.4.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  xml2json: ^6.2.7
dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  lint: ^2.8.0
  riverpod_generator: ^2.6.5
dependency_overrides:
  collection: ^1.19.1
  flutter_inappwebview: ^6.1.5
flutter:
  uses-material-design: true
  assets:
    - assets/images/
