name: mno_shared
description: Contains the definitions of the custom types (model) used across the Readium-2 Dart projects.
version: 0.1.3
homepage: https://github.com/Mantano/mno_shared_dart
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^4.0.7
  collection: ^1.19.1
  crypto: ^3.0.6
  dartx: ^1.2.0
  dfunc: ^0.10.0
  equatable: ^2.0.7
  fimber: ^0.7.0
  http: ^1.3.0
  image: ^4.5.4
  intl: any
  meta: ^1.16.0
  universal_io: ^2.2.2
  xml: ^6.5.0
  mno_commons:
    path: ../commons
  path: ^1.8.3

dev_dependencies:
  image_compare:
    # From https://github.com/Mantano/iridium/pull/75/commits/b827f036e58c860499cd851d8b279ddae561351c
    # TODO: Use upstream version when https://github.com/nitinramadoss/image_compare/pull/10 is merged
    git:
      url: https://github.com/838/image_compare
      ref: upgrade/deps
  lints: ^6.0.0
  test: ^1.25.15
